<?xml version="1.0"?>
<package format="3">
  <name>tf_tools</name>
  <version>0.0.0</version>
  <description>TF tools for odom broadcasting</description>

  <maintainer email="user@todo.todo">user</maintainer>
  <license>Apache-2.0</license>

  <!-- Build tool -->
  <buildtool_depend>ament_python</buildtool_depend>

  <!-- Dependencies -->
  <depend>rclpy</depend>
  <depend>nav_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>tf2_ros</depend>

  <!-- Export -->
  <export>
    <build_type>ament_python</build_type>
  </export>
</package>